spring:
  application:
    name: project-service
  cloud:
    config:
      uri: http://localhost:8888
      username: config-admin
      password: config-pass
      fail-fast: true
      retry:
        initial-interval: 1000
        multiplier: 1.1
        max-attempts: 6
        max-interval: 2000

logging:
  level:
    com.projecttaskhub.project: DEBUG
    org.springframework.security: DEBUG